# inference_and_save.py

import torch
import os
import csv
import json
import threading
from collections import defaultdict
from django.utils import timezone
from learning.models import StudentDiagnosis, User, KnowledgePoint, DiagnosisModel, KnowledgeGraph
from CMD_survey.model import NCDM

# The teacher-end inference path now has two branches:
# 1. legacy models that load exported files and local checkpoints here;
# 2. CDF-family models that are delegated to an adapter layer.
# The guarded import lets the non-CDF path keep working even if the local
# bridge file has been cleaned up from the workspace.
try:
    from cdf_bridge import is_cdf_model, run_cdf_diagnosis_pipeline
    CDF_BRIDGE_AVAILABLE = True
except ImportError:
    CDF_BRIDGE_AVAILABLE = False

    def is_cdf_model(model_name):
        return model_name in {'IdpCDF', 'HierCDF', 'ConCDF', 'PCG-CDF'}

    def run_cdf_diagnosis_pipeline(*args, **kwargs):
        raise RuntimeError('cdf_bridge.py is missing')

def save_to_database_async(subject_id, model_id, mastery_vectors, student_known_kps, user_mapping, kp_mapping, un):
    """异步保存诊断数据到数据库"""

    def _save():
        try:
            from learning.models import StudentDiagnosis, User, KnowledgePoint, DiagnosisModel
            from django.utils import timezone

            diagnosis_model = DiagnosisModel.objects.get(id=model_id)
            saved_count = 0

            for new_student_id, known_kps in student_known_kps.items():
                student_original_id = user_mapping.get(new_student_id)
                if not student_original_id:
                    continue

                student = User.objects.filter(id=student_original_id, user_type='student').first()
                if not student:
                    continue

                mastery_vector = mastery_vectors[new_student_id - 1]

                for new_kp_id in known_kps:
                    mastery = float(mastery_vector[new_kp_id - 1])
                    kp_original_id = kp_mapping.get(new_kp_id)

                    if not kp_original_id:
                        continue

                    knowledge_point = KnowledgePoint.objects.filter(id=kp_original_id).first()
                    if not knowledge_point:
                        continue

                    StudentDiagnosis.objects.update_or_create(
                        student=student,
                        knowledge_point=knowledge_point,
                        diagnosis_model=diagnosis_model,
                        defaults={
                            'mastery_level': round(mastery, 3),
                            'last_practiced': timezone.now()
                        }
                    )
                    saved_count += 1

            print(f"后台保存完成：已保存/更新 {saved_count} 条诊断记录")
        except Exception as e:
            print(f"后台保存失败: {str(e)}")

    thread = threading.Thread(target=_save)
    thread.daemon = True
    thread.start()


def infer_and_get_diagnosis_data(subject_id, model_id, model_name):
    """
    推理获取诊断数据（返回前端数据，后台异步保存到数据库）
    """
    # 1. 数据目录

        # CDF models do not use the legacy "load .pth from data/<subject_id>/models"
    # logic below. They need extra inputs such as graph data and service-side
    # result assembly, so they are short-circuited into the bridge branch.
    if is_cdf_model(model_name):
        if not CDF_BRIDGE_AVAILABLE:
            print(
                f"CDF model {model_name} requires learning/diagnosis/cdf_bridge.py, "
                "but that file is currently missing."
            )
            return None
        try:
            result = run_cdf_diagnosis_pipeline(
                subject_id=subject_id,
                model_id=model_id,
                model_name=model_name,
                save_to_db=True,
                force_graph_refresh=False,
            )
            if 'error' in result:
                print(f"CDF模型 {model_name} 推理失败: {result['error']}")
                return None
            return result
        except Exception as e:
            print(f"CDF模型 {model_name} 推理异常: {str(e)}")
            return None

    # Legacy models continue to read the exported dataset package generated by
    # `export_training_data(subject_id)` in views_diagnosis.run_diagnosis().

    data_dir = os.path.join(os.path.dirname(__file__), 'data', str(subject_id))

    # 2. 读取配置
    with open(os.path.join(data_dir, 'config.txt'), 'r') as f:
        f.readline()
        un, en, kn = f.readline().split(',')
        un, en, kn = int(un), int(en), int(kn)

    print(f"学生数: {un}, 习题数: {en}, 知识点数: {kn}")

    # 3. 读取映射表
    user_mapping = {}
    kp_mapping = {}

    with open(os.path.join(data_dir, 'homologous.csv'), 'r', encoding='utf-8') as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            if row[0]:
                user_mapping[int(row[0])] = int(row[1])
            if row[4]:
                kp_mapping[int(row[4])] = int(row[5])

    # 4. 读取 log_data.json
    log_data_path = os.path.join(data_dir, 'log_data.json')
    with open(log_data_path, 'r', encoding='utf-8') as f:
        all_logs = json.load(f)

    student_known_kps = defaultdict(set)
    for log in all_logs:
        student_new_id = log['user_id']
        for kp in log['knowledge_code']:
            student_known_kps[student_new_id].add(kp)

    # 5. 加载模型并推理
    device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
    model_path = os.path.join(data_dir, 'models', f'{model_name}.pth')

    if model_name.upper() == 'NCDM':
        cdm = NCDM.NCDM(kn, en, un)
        cdm.load(model_path)
        cdm.ncdm_net.to(device)
        cdm.ncdm_net.eval()

        with torch.no_grad():
            student_indices = torch.LongTensor(list(range(un))).to(device)
            stu_emb = cdm.ncdm_net.student_emb(student_indices)
            mastery_vectors = torch.sigmoid(stu_emb).cpu().numpy()

        print(f"掌握度矩阵形状: {mastery_vectors.shape}")
    else:
        print(f"模型 {model_name} 暂不支持推理")
        return None

    # 6. 异步保存到数据库（不阻塞）
    save_to_database_async(subject_id, model_id, mastery_vectors, student_known_kps,
                           user_mapping, kp_mapping, un)

    # 7. 获取原始知识点信息（用于前端返回）
    all_knowledge_points = KnowledgePoint.objects.filter(subject_id=subject_id)
    kp_info = {kp.id: kp.name for kp in all_knowledge_points}

    # 8. 构建知识点平均掌握度（用于前端）
    kp_mastery_sum = defaultdict(float)
    kp_count = defaultdict(int)

    diagnosis_results = {}

    for new_student_id, known_kps in student_known_kps.items():
        student_original_id = user_mapping.get(new_student_id)
        if not student_original_id:
            continue

        mastery_vector = mastery_vectors[new_student_id - 1]
        student_mastery = {}
        weak_points = []

        for new_kp_id in known_kps:
            mastery = float(mastery_vector[new_kp_id - 1])
            kp_original_id = kp_mapping.get(new_kp_id)

            if not kp_original_id:
                continue

            kp_mastery_sum[kp_original_id] += mastery
            kp_count[kp_original_id] += 1

            student_mastery[str(kp_original_id)] = round(mastery, 3)

            if mastery < 0.6:
                weak_points.append({
                    'id': int(kp_original_id),
                    'name': kp_info.get(kp_original_id, '未知'),
                    'mastery': round(mastery, 3)
                })

        overall_score = round(sum(student_mastery.values()) / len(student_mastery), 3) if student_mastery else 0.0

        # 获取学生名称
        student_obj = User.objects.filter(id=student_original_id).first()
        student_name = student_obj.username if student_obj else f"学生{student_original_id}"

        diagnosis_results[student_original_id] = {
            'student_id': student_original_id,
            'student_name': student_name,
            'overall_score': overall_score,
            'knowledge_mastery': student_mastery,
            'weak_points': weak_points,
            'answer_count': len(known_kps)
        }

    # 9. 构建知识点列表
    knowledge_points_data = []
    for kp_id, name in kp_info.items():
        avg_mastery = round((kp_mastery_sum.get(kp_id, 0) / kp_count.get(kp_id, 1)) * 100, 3)
        knowledge_points_data.append({
            'id': int(kp_id),
            'name': name,
            'avg_mastery': avg_mastery,
            'exercise_count': 0
        })

    # 10. 获取知识点关系
    knowledge_relations = []
    kg_relations = KnowledgeGraph.objects.filter(subject_id=subject_id).values_list('source_id', 'target_id')
    for source_id, target_id in kg_relations:
        knowledge_relations.append({'source': int(source_id), 'target': int(target_id)})

    return {
        'knowledge_points': knowledge_points_data,
        'diagnosis_results': diagnosis_results,
        'knowledge_relations': knowledge_relations,
        'total_students': len(diagnosis_results),
        'total_kp_count': len(knowledge_points_data)
    }