# Generated by Django 4.1 on 2025-11-12 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="科目名称")),
                ("description", models.TextField(blank=True, verbose_name="科目描述")),
            ],
            options={"verbose_name": "科目", "verbose_name_plural": "科目",},
        ),
        migrations.CreateModel(
            name="KnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="知识点名称")),
                ("description", models.TextField(blank=True, verbose_name="知识点描述")),
                ("level", models.IntegerField(default=1, verbose_name="难度等级")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="learning.knowledgepoint",
                        verbose_name="父知识点",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="所属科目",
                    ),
                ),
            ],
            options={"verbose_name": "知识点", "verbose_name_plural": "知识点",},
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "problemsets",
                    models.CharField(default="", max_length=200, verbose_name="习题集ID"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="习题标题")),
                ("content", models.TextField(verbose_name="习题内容")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("single", "单选题"),
                            ("multiple", "多选题"),
                            ("text", "简答题"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="题型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="所属科目",
                    ),
                ),
            ],
            options={"verbose_name": "习题", "verbose_name_plural": "习题",},
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="选项内容")),
                ("is_correct", models.BooleanField(default=False, verbose_name="是否正确")),
                ("order", models.IntegerField(default=0, verbose_name="选项顺序")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="learning.exercise",
                        verbose_name="所属习题",
                    ),
                ),
            ],
            options={
                "verbose_name": "选项",
                "verbose_name_plural": "选项",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AnswerLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_answer", models.TextField(blank=True, verbose_name="文本答案")),
                ("is_correct", models.BooleanField(null=True, verbose_name="是否正确")),
                ("time_spent", models.IntegerField(default=0, verbose_name="答题耗时(秒)")),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.exercise",
                        verbose_name="习题",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(
                        blank=True, to="learning.choice", verbose_name="选择的选项"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={"verbose_name": "答题记录", "verbose_name_plural": "答题记录",},
        ),
        migrations.CreateModel(
            name="StudentDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mastery_level", models.FloatField(default=0.0, verbose_name="掌握程度")),
                (
                    "last_practiced",
                    models.DateTimeField(auto_now=True, verbose_name="最后练习时间"),
                ),
                ("practice_count", models.IntegerField(default=0, verbose_name="练习次数")),
                ("correct_count", models.IntegerField(default=0, verbose_name="正确次数")),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.knowledgepoint",
                        verbose_name="知识点",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生诊断",
                "verbose_name_plural": "学生诊断",
                "unique_together": {("student", "knowledge_point")},
            },
        ),
        migrations.CreateModel(
            name="QMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=1.0, verbose_name="权重")),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.exercise",
                        verbose_name="习题",
                    ),
                ),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.knowledgepoint",
                        verbose_name="知识点",
                    ),
                ),
            ],
            options={
                "verbose_name": "Q矩阵",
                "verbose_name_plural": "Q矩阵",
                "unique_together": {("exercise", "knowledge_point")},
            },
        ),
    ]
