# Generated by Django 4.1 on 2025-12-09 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模型名称")),
                ("description", models.TextField(blank=True, verbose_name="模型描述")),
                (
                    "algorithm_type",
                    models.CharField(
                        choices=[
                            ("dina", "DINA模型"),
                            ("irt", "IRT模型"),
                            ("bkt", "BKT模型"),
                            ("neural", "神经网络"),
                        ],
                        max_length=50,
                        verbose_name="算法类型",
                    ),
                ),
                ("parameters", models.JSONField(default=dict, verbose_name="模型参数")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
