# Generated by Django 4.1 on 2025-11-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="exercise", name="created_at",),
    ]
