# Generated by Django 4.1 on 2025-11-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exercise", old_name="created_by", new_name="creator",
        ),
        migrations.AddField(
            model_name="exercise",
            name="answer",
            field=models.CharField(default=None, max_length=500, verbose_name="答案"),
        ),
        migrations.AddField(
            model_name="exercise",
            name="option_text",
            field=models.CharField(default=None, max_length=500, verbose_name="选项内容"),
        ),
    ]
