# Generated by Django 4.1 on 2025-11-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "learning",
            "0002_rename_created_by_exercise_creator_exercise_answer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="option_text",
            field=models.CharField(default=None, max_length=1000, verbose_name="选项内容"),
        ),
    ]
