# Generated by Django 4.1 on 2025-12-24 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_diagnosismodel_teachersubject_studentsubject"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeGraph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing",
                        to="learning.knowledgepoint",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="所属科目",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming",
                        to="learning.knowledgepoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识点关系",
                "verbose_name_plural": "知识点关系",
                "unique_together": {("subject", "source", "target")},
            },
        ),
    ]
