# Generated by Django 4.1 on 2025-11-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_remove_exercise_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="question_type",
            field=models.CharField(default="single", max_length=10, verbose_name="题型"),
        ),
    ]
