# Generated by Django 4.1 on 2025-12-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0002_diagnosismodel"),
    ]

    operations = [
        migrations.RemoveField(model_name="diagnosismodel", name="algorithm_type",),
        migrations.RemoveField(model_name="diagnosismodel", name="parameters",),
    ]
