# Generated by Django 4.1 on 2026-01-06 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0003_knowledgegraph"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knowledge_mastery", models.JSONField(verbose_name="知识点掌握程度")),
                ("overall_score", models.FloatField(verbose_name="总体掌握度")),
                ("weak_points", models.JSONField(verbose_name="薄弱知识点")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="诊断时间"),
                ),
                (
                    "diagnosis_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.diagnosismodel",
                        verbose_name="使用模型",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="学生",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="科目",
                    ),
                ),
            ],
            options={"verbose_name": "诊断结果", "verbose_name_plural": "诊断结果",},
        ),
    ]
