# Generated by Django 4.1 on 2025-11-29 05:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0003_alter_exercise_option_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=learning.models.exercise_file_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "txt",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                        verbose_name="习题文件",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("txt", "文本文件"),
                            ("pdf", "PDF文件"),
                            ("doc", "Word文档"),
                            ("docx", "Word文档"),
                            ("xls", "Excel文件"),
                            ("xlsx", "Excel文件"),
                        ],
                        max_length=10,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("error", "处理失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理完成时间"),
                ),
                (
                    "exercise_count",
                    models.IntegerField(default=0, verbose_name="生成的习题数量"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="所属科目",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "习题文件",
                "verbose_name_plural": "习题文件",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
