# Generated by Django 4.1 on 2026-01-11 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0004_diagnosisresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdiagnosis",
            name="diagnosis_model",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.diagnosismodel",
                verbose_name="使用模型",
            ),
        ),
    ]
