# Generated by Django 4.1 on 2026-01-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0005_studentdiagnosis_diagnosis_model"),
    ]

    operations = [
        migrations.DeleteModel(name="DiagnosisResult",),
    ]
