# Generated by Django 4.1 on 2026-01-11 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0006_delete_diagnosisresult"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="studentdiagnosis", unique_together=set(),),
    ]
