# Generated by Django 4.1 on 2026-01-11 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0007_alter_studentdiagnosis_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="answerlog",
            name="subject",
            field=models.ForeignKey(
                default=584381,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.subject",
                verbose_name="所属科目",
            ),
        ),
    ]
