# Generated by Django 4.1 on 2026-01-14 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0008_answerlog_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerlog",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="learning.subject",
                verbose_name="所属科目",
            ),
        ),
    ]
