# Generated by Django 4.1 on 2026-01-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0009_alter_answerlog_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="exercise",
            name="solution",
            field=models.TextField(blank=True, null=True, verbose_name="答案解析"),
        ),
    ]
