# Generated by Django 4.1 on 2026-01-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0010_add_solution_and_created_at_to_exercise"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answerlog",
            name="text_answer",
            field=models.TextField(blank=True, default=None, verbose_name="文本答案"),
        ),
    ]
