# Generated by Django 4.1 on 2026-01-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0012_exercisefavorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="subjects/", verbose_name="科目图片"
            ),
        ),
    ]
