# Generated by Django 4.1 on 2026-01-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0013_subject_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="static/images/subject/",
                verbose_name="科目图片",
            ),
        ),
    ]
