# Generated by Django 4.1 on 2026-01-22 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0014_alter_subject_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="subject/", verbose_name="科目图片"
            ),
        ),
    ]
