# Generated by Django 4.1 on 2026-02-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0016_dataset_alter_subject_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosismodel",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "诊断模型",
                "verbose_name_plural": "诊断模型",
            },
        ),
        migrations.AddField(
            model_name="diagnosismodel",
            name="paper_link",
            field=models.URLField(blank=True, verbose_name="论文链接"),
        ),
    ]
