# Generated by Django 4.1 on 2026-02-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0017_alter_diagnosismodel_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diagnosismodel",
            options={
                "ordering": ["id"],
                "verbose_name": "诊断模型",
                "verbose_name_plural": "诊断模型",
            },
        ),
        migrations.AddField(
            model_name="diagnosismodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("probability", "Probability"),
                    ("nn", "NN"),
                    ("gnn", "GNN"),
                    ("llm", "LLM"),
                ],
                default="probability",
                max_length=20,
                verbose_name="模型分类",
            ),
        ),
    ]
