# Generated by Django 4.1 on 2026-04-28 04:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0019_experiment_modeltrainingresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="资料标题")),
                ("description", models.TextField(blank=True, verbose_name="资料描述")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("课件", "课件/教案"),
                            ("讲义", "讲义/笔记"),
                            ("习题集", "习题集/题库"),
                            ("视频", "视频资料"),
                            ("音频", "音频资料"),
                            ("图片", "图片资料"),
                            ("其他", "其他资料"),
                        ],
                        default="课件",
                        max_length=20,
                        verbose_name="资料类型",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=learning.models.resource_file_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "docx",
                                    "xlsx",
                                    "pptx",
                                    "pdf",
                                    "txt",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "mp4",
                                    "mp3",
                                    "wav",
                                ]
                            )
                        ],
                        verbose_name="资料文件",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("docx", "Word文档"),
                            ("xlsx", "Excel文件"),
                            ("pptx", "PowerPoint文档"),
                            ("pdf", "PDF文件"),
                            ("txt", "文本文件"),
                            ("jpg", "JPEG图片"),
                            ("png", "PNG图片"),
                            ("gif", "GIF图片"),
                            ("mp4", "MP4视频"),
                            ("mp3", "MP3音频"),
                            ("wav", "WAV音频"),
                            ("其他", "其他文件"),
                        ],
                        max_length=10,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("error", "处理失败"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="处理状态",
                    ),
                ),
                ("is_public", models.BooleanField(default=True, verbose_name="公开给学生")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理完成时间"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.subject",
                        verbose_name="所属科目",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教学资料",
                "verbose_name_plural": "教学资料",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
