# Generated by Django 4.1 on 2026-04-28 04:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0020_resourcefile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TextbookCourseBuilder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=200, verbose_name="课程名称")),
                (
                    "subject_description",
                    models.TextField(blank=True, verbose_name="课程描述"),
                ),
                (
                    "textbook_file",
                    models.FileField(
                        upload_to=learning.models.textbook_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                        verbose_name="PDF课本",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="原始文件名"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("extracting_text", "提取文本中"),
                            ("analyzing_content", "分析内容中"),
                            ("generating_exercises", "生成习题中"),
                            ("extracting_knowledge", "提取知识点中"),
                            ("building_graph", "构建图谱中"),
                            ("completed", "已完成"),
                            ("error", "处理失败"),
                        ],
                        default="pending",
                        max_length=30,
                        verbose_name="处理状态",
                    ),
                ),
                ("extracted_text", models.TextField(blank=True, verbose_name="提取的文本")),
                ("chapter_count", models.IntegerField(default=0, verbose_name="章节数量")),
                (
                    "exercise_count",
                    models.IntegerField(default=0, verbose_name="生成的习题数量"),
                ),
                (
                    "knowledge_point_count",
                    models.IntegerField(default=0, verbose_name="提取的知识点数量"),
                ),
                (
                    "relationship_count",
                    models.IntegerField(default=0, verbose_name="知识点关系数量"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="处理完成时间"),
                ),
                (
                    "generated_subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="learning.subject",
                        verbose_name="生成的课程",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "课本快速构建",
                "verbose_name_plural": "课本快速构建",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
