# Generated by Django 4.1 on 2026-04-28 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0021_textbookcoursebuilder"),
    ]

    operations = [
        migrations.AddField(
            model_name="textbookcoursebuilder",
            name="exercises_approved",
            field=models.IntegerField(default=0, verbose_name="通过审核的习题数量"),
        ),
        migrations.AddField(
            model_name="textbookcoursebuilder",
            name="exercises_reviewed",
            field=models.IntegerField(default=0, verbose_name="已审核习题数量"),
        ),
        migrations.AddField(
            model_name="textbookcoursebuilder",
            name="knowledge_points_approved",
            field=models.IntegerField(default=0, verbose_name="通过审核的知识点数量"),
        ),
        migrations.AddField(
            model_name="textbookcoursebuilder",
            name="knowledge_points_reviewed",
            field=models.IntegerField(default=0, verbose_name="已审核知识点数量"),
        ),
        migrations.AddField(
            model_name="textbookcoursebuilder",
            name="relationships_approved",
            field=models.IntegerField(default=0, verbose_name="通过审核的关系数量"),
        ),
        migrations.AddField(
            model_name="textbookcoursebuilder",
            name="relationships_reviewed",
            field=models.IntegerField(default=0, verbose_name="已审核关系数量"),
        ),
        migrations.AddField(
            model_name="textbookcoursebuilder",
            name="review_completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核完成时间"),
        ),
        migrations.AddField(
            model_name="textbookcoursebuilder",
            name="review_started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="审核开始时间"),
        ),
        migrations.AlterField(
            model_name="textbookcoursebuilder",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("extracting_text", "提取文本中"),
                    ("analyzing_content", "分析内容中"),
                    ("generating_exercises", "生成习题中"),
                    ("extracting_knowledge", "提取知识点中"),
                    ("building_graph", "构建图谱中"),
                    ("review_pending", "待审核"),
                    ("reviewing_exercises", "审核习题中"),
                    ("reviewing_knowledge", "审核知识点中"),
                    ("reviewing_graph", "审核图谱中"),
                    ("completed", "已完成"),
                    ("error", "处理失败"),
                ],
                default="pending",
                max_length=30,
                verbose_name="处理状态",
            ),
        ),
        migrations.CreateModel(
            name="TextbookReviewRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(max_length=50, verbose_name="关系类型"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="是否通过审核"),
                ),
                (
                    "is_rejected",
                    models.BooleanField(default=False, verbose_name="是否被拒绝"),
                ),
                ("review_notes", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.textbookcoursebuilder",
                        verbose_name="构建器",
                    ),
                ),
                (
                    "from_knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewed_from_relationships",
                        to="learning.knowledgepoint",
                        verbose_name="源知识点",
                    ),
                ),
                (
                    "to_knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviewed_to_relationships",
                        to="learning.knowledgepoint",
                        verbose_name="目标知识点",
                    ),
                ),
            ],
            options={
                "verbose_name": "课本关系审核",
                "verbose_name_plural": "课本关系审核",
                "unique_together": {
                    (
                        "builder",
                        "from_knowledge_point",
                        "to_knowledge_point",
                        "relationship_type",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="TextbookReviewKnowledgePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=200, verbose_name="原始名称"),
                ),
                (
                    "original_description",
                    models.TextField(blank=True, verbose_name="原始描述"),
                ),
                (
                    "reviewed_name",
                    models.CharField(blank=True, max_length=200, verbose_name="审核后名称"),
                ),
                (
                    "reviewed_description",
                    models.TextField(blank=True, verbose_name="审核后描述"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="是否通过审核"),
                ),
                (
                    "is_modified",
                    models.BooleanField(default=False, verbose_name="是否已修改"),
                ),
                ("review_notes", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.textbookcoursebuilder",
                        verbose_name="构建器",
                    ),
                ),
                (
                    "knowledge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.knowledgepoint",
                        verbose_name="知识点",
                    ),
                ),
            ],
            options={
                "verbose_name": "课本知识点审核",
                "verbose_name_plural": "课本知识点审核",
                "unique_together": {("builder", "knowledge_point")},
            },
        ),
        migrations.CreateModel(
            name="TextbookReviewExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_content", models.TextField(verbose_name="原始内容")),
                (
                    "reviewed_content",
                    models.TextField(blank=True, verbose_name="审核后内容"),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="是否通过审核"),
                ),
                (
                    "is_modified",
                    models.BooleanField(default=False, verbose_name="是否已修改"),
                ),
                ("review_notes", models.TextField(blank=True, verbose_name="审核备注")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="审核时间"),
                ),
                (
                    "builder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.textbookcoursebuilder",
                        verbose_name="构建器",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.exercise",
                        verbose_name="习题",
                    ),
                ),
            ],
            options={
                "verbose_name": "课本习题审核",
                "verbose_name_plural": "课本习题审核",
                "unique_together": {("builder", "exercise")},
            },
        ),
    ]
