# Generated by Django 4.1 on 2026-04-29 10:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("learning", "0022_textbookcoursebuilder_exercises_approved_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="studentdiagnosis",
            unique_together={("student", "knowledge_point", "diagnosis_model")},
        ),
    ]
