# Generated by Django 3.2 on 2026-05-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0023_alter_studentdiagnosis_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='score',
            field=models.DecimalField(decimal_places=1, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='knowledgepoint',
            name='similar_points',
            field=models.ManyToManyField(blank=True, related_name='_learning_knowledgepoint_similar_points_+', to='learning.KnowledgePoint', verbose_name='相似知识点'),
        ),
    ]
