# Generated by Django 3.2.25 on 2026-05-10 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0024_auto_20260509_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlog',
            name='ai_feedback',
            field=models.TextField(blank=True, verbose_name='AI评分反馈'),
        ),
        migrations.AddField(
            model_name='answerlog',
            name='feedback',
            field=models.TextField(blank=True, verbose_name='评分反馈'),
        ),
        migrations.AddField(
            model_name='answerlog',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='批改时间'),
        ),
        migrations.AddField(
            model_name='answerlog',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL, verbose_name='批改人'),
        ),
        migrations.AddField(
            model_name='answerlog',
            name='grading_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='评分置信度'),
        ),
        migrations.AddField(
            model_name='answerlog',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='得分'),
        ),
    ]
