# Generated by Django 3.2.25 on 2026-05-11 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class AddFieldIfNotExists(migrations.AddField):
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.model_name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            existing_columns = {
                column.name
                for column in schema_editor.connection.introspection.get_table_description(cursor, table_name)
            }

        if self.name in existing_columns:
            return

        super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0025_subject_dataset'),
    ]

    operations = [
        AddFieldIfNotExists(
            model_name='answerlog',
            name='ai_feedback',
            field=models.TextField(blank=True, default='', verbose_name='AI批改反馈'),
        ),
        AddFieldIfNotExists(
            model_name='answerlog',
            name='feedback',
            field=models.TextField(blank=True, default='', verbose_name='教师批改反馈'),
        ),
        AddFieldIfNotExists(
            model_name='answerlog',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='批改时间'),
        ),
        AddFieldIfNotExists(
            model_name='answerlog',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL, verbose_name='批改教师'),
        ),
        AddFieldIfNotExists(
            model_name='answerlog',
            name='grading_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='批改置信度'),
        ),
        AddFieldIfNotExists(
            model_name='answerlog',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='得分'),
        ),
    ]

