# Generated by Django 3.2.25 on 2026-05-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_subject_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegraph',
            name='relationship_type',
            field=models.CharField(choices=[('隶属', '隶属'), ('关联', '关联'), ('前置', '前置'), ('相似', '相似')], default='关联', max_length=10, verbose_name='关系类型'),
        ),
    ]
