# Generated by Django 3.2.25 on 2026-05-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0026_auto_20260513_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='extracted_text',
            field=models.TextField(blank=True, verbose_name='提取的文本内容'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='resource_type',
            field=models.CharField(choices=[('教案', '教案'), ('课件', '课件'), ('其他', '其他资料')], default='课件', max_length=20, verbose_name='资料类型'),
        ),
    ]
