# Generated by Django 3.2.25 on 2026-05-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0027_auto_20260513_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegraph',
            name='relation_source',
            field=models.CharField(choices=[('教材', '教材'), ('教案', '教案'), ('课件', '课件')], default='教材', max_length=20, verbose_name='关系来源'),
        ),
        migrations.AlterUniqueTogether(
            name='knowledgegraph',
            unique_together={('subject', 'source', 'target', 'relation_source')},
        ),
    ]
