# Generated by Django 3.2.25 on 2026-05-13 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0028_add_relation_source_to_knowledgegraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceKnowledgeExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('review_pending', '待审核'), ('reviewing_knowledge', '审核知识点中'), ('reviewing_graph', '审核图谱中'), ('completed', '已完成'), ('error', '处理失败')], default='pending', max_length=30, verbose_name='处理状态')),
                ('kp_count', models.IntegerField(default=0, verbose_name='提取的知识点数量')),
                ('rel_count', models.IntegerField(default=0, verbose_name='提取的关系数量')),
                ('kp_reviewed', models.IntegerField(default=0, verbose_name='已审核知识点数量')),
                ('kp_approved', models.IntegerField(default=0, verbose_name='通过的知识点数量')),
                ('rel_reviewed', models.IntegerField(default=0, verbose_name='已审核关系数量')),
                ('rel_approved', models.IntegerField(default=0, verbose_name='通过的关系数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('resource_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.resourcefile', verbose_name='资源文件')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subject', verbose_name='所属科目')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='教师')),
            ],
            options={
                'verbose_name': '资源知识提取',
                'verbose_name_plural': '资源知识提取',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceReviewRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=50, verbose_name='关系类型')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否通过审核')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='是否被拒绝')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.resourceknowledgeextraction', verbose_name='提取记录')),
                ('from_knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_reviewed_from', to='learning.knowledgepoint', verbose_name='源知识点')),
                ('to_knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_reviewed_to', to='learning.knowledgepoint', verbose_name='目标知识点')),
            ],
            options={
                'verbose_name': '资源关系审核',
                'verbose_name_plural': '资源关系审核',
            },
        ),
        migrations.CreateModel(
            name='ResourceReviewKnowledgePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=200, verbose_name='原始名称')),
                ('reviewed_name', models.CharField(blank=True, max_length=200, verbose_name='审核后名称')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否通过审核')),
                ('review_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('extraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.resourceknowledgeextraction', verbose_name='提取记录')),
                ('knowledge_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.knowledgepoint', verbose_name='知识点')),
            ],
            options={
                'verbose_name': '资源知识点审核',
                'verbose_name_plural': '资源知识点审核',
                'unique_together': {('extraction', 'knowledge_point')},
            },
        ),
    ]
