# Generated by Django 3.2.25 on 2026-05-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0029_add_resource_extraction_review_models'),
        ('learning', '0033_update_dncdm_dataset_names'),
    ]

    operations = [
    ]
