# Generated by Django 3.2.25 on 2026-05-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0034_merge_20260514_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoint',
            name='sources',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='所属来源（教材/教案/课件）'),
        ),
    ]
