# Generated by Django 3.2.25 on 2026-05-18 06:32

import django.core.validators
from django.db import migrations, models
import learning.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0035_knowledgepoint_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefile',
            name='exercise_count',
            field=models.IntegerField(default=0, verbose_name='习题数量'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='file',
            field=models.FileField(upload_to=learning.models.resource_file_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['docx', 'xlsx', 'xls', 'pptx', 'pdf', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'mp4', 'mp3', 'wav'])], verbose_name='资料文件'),
        ),
        migrations.AlterField(
            model_name='resourcefile',
            name='resource_type',
            field=models.CharField(choices=[('教材', '教材'), ('教案', '教案'), ('课件', '课件'), ('习题', '习题'), ('其他', '其他资料')], default='课件', max_length=20, verbose_name='资料类型'),
        ),
    ]
