# Generated by Django 3.2.25 on 2026-05-18 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0036_auto_20260518_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgegraph',
            name='resource_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.resourcefile', verbose_name='所属资料文件'),
        ),
    ]
