# Generated by Django 3.2.25 on 2026-05-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0037_knowledgegraph_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgepoint',
            name='resource_files',
            field=models.ManyToManyField(blank=True, to='learning.ResourceFile', verbose_name='关联资源文件'),
        ),
    ]
