# Generated by Django 3.2.25 on 2026-06-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0025_auto_20260511_0218'),
        ('learning', '0038_add_knowledgepoint_resource_files'),
    ]

    operations = [
    ]
