# Generated by Django 3.2.25 on 2026-06-03 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0039_merge_20260603_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcereviewknowledgepoint',
            name='confidence',
            field=models.CharField(choices=[('高', '高'), ('低', '低')], default='高', max_length=2, verbose_name='LLM置信度'),
        ),
        migrations.AddField(
            model_name='resourcereviewrelationship',
            name='confidence',
            field=models.CharField(choices=[('高', '高'), ('低', '低')], default='高', max_length=2, verbose_name='LLM置信度'),
        ),
        migrations.AlterField(
            model_name='answerlog',
            name='ai_feedback',
            field=models.TextField(blank=True, default='', verbose_name='AI批改反馈'),
        ),
        migrations.AlterField(
            model_name='answerlog',
            name='feedback',
            field=models.TextField(blank=True, default='', verbose_name='教师批改反馈'),
        ),
        migrations.AlterField(
            model_name='answerlog',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL, verbose_name='批改教师'),
        ),
        migrations.AlterField(
            model_name='answerlog',
            name='grading_confidence',
            field=models.FloatField(blank=True, null=True, verbose_name='批改置信度'),
        ),
    ]
