# Generated by Django 3.2.25 on 2026-06-08 13:30
# 多学科融合关系审核改为「无独立审核表」设计：
#   - 不再创建 FusionRelationReview 表；
#   - 仅保留 KnowledgeGraph.relation_source 增加 '融合' 选项（Django 层 choices，
#     列类型不变，对已有数据无影响）。

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0040_add_confidence_to_review_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgegraph',
            name='relation_source',
            field=models.CharField(choices=[('教材', '教材'), ('教案', '教案'), ('课件', '课件'), ('融合', '融合')], default='教材', max_length=20, verbose_name='关系来源'),
        ),
    ]
