# Generated by Django 3.2.25 on 2026-08-04 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0041_auto_20260608_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='learning.subjectcomment', verbose_name='回复的评论')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='learning.subject', verbose_name='所属课程')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_comments', to=settings.AUTH_USER_MODEL, verbose_name='发表人')),
            ],
            options={
                'verbose_name': '学生社区评论',
                'verbose_name_plural': '学生社区评论',
                'ordering': ['-created_at'],
            },
        ),
    ]
